### ISSUE TITLE
Support for Wagmi v2

### ISSUE THREAD

**Issue by thedevbirb** [magiclabs/wagmi-magic-connector#15]
Reference: https://wagmi.sh/react/guides/migrate-from-v1-to-v2

Thanks for the attention!

**Comment by mwawrusch** [comment]
+1 for that.

**Comment by mjafri118** [comment]
has anyone made a connector function yet? https://wagmi.sh/dev/creating-connectors

**Comment by Royal-lobster** [comment]
> has anyone made a connector function yet? [wagmi.sh/dev/creating-connectors](https://wagmi.sh/dev/creating-connectors)

We are working on this, will push a PR asap

**Comment by yulafezmesi** [comment]
hey! is there any update for this?

**Comment by jamesrp13** [comment]
The PR has been merged. Update is available in version 2.0.0
